- hosts: all
  become: yes

  tasks:
    - name: 1. Atualizar repositórios (Cache)
      command: zypper refresh

    - name: 2. Aplicar atualizações
      zypper:
        name: '*'
        state: latest
      register: update_result

    - name: 3. Reiniciar servidor (Obrigatório)
      reboot:
        msg: "Reboot mandatório pós-manutenção"
        reboot_timeout: 600

    - name: 4. Exibir relatório final
      debug:
        msg: >
          PROCESSO FINALIZADO:
          - Status da atualização: {{ 'Sucesso/Alterado' if update_result.changed else 'Sem alterações' }}
          - Reboot realizado.